site_name: MkModel

theme:
  name: null
  custom_dir: material
  palette:
    scheme: mkmodel
  font: false
  language: zh
  features:
    # - navigation.instant
    - navigation.tabs
    - tabs.changeicon
    - toc.autohide
  icons:
    home: custom/model3
    general: custom/model1
    test_tab: custom/model2
  icon:
    logo: custom/computer1
  favicon: images/favicon.png

extra_css:
  - css/general.css
  - css/fonts.css
  - css/code-admonition.css
  - css/generalcy.css
  - css/katex.css
  - css/tables.css
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css'

extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js'
  - 'js/katex.js'
  - 'js/font.js'
  - 'js/table.js'
  - 'js/code_style.js'

nav:
  - general:
      - general: general/index.md
      - code: general/code.md
      - nested:
          - n1: general/nested/1.md
  - test tab:
      - general: test_tab/index.md
      - code: test_tab/code.md
      - nested:
          - n2: test_tab/nested/2.md

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: table
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: ðŸŽ¶
      toc_depth: 6 # Define the range of levels to be included in the table of contents

plugins:
  - search